In [1]:
import arff

In [31]:
from skmultilearn.dataset import load_dataset

In [32]:
X_train, y_train, feature_names, label_names = load_dataset('emotions', 'train')
X_test, y_test, _, _ =load_dataset('emotions', 'test')

emotions:train - exists, not redownloading
emotions:test - exists, not redownloading


In [33]:
type(label_names)

list

In [34]:
type(y_train)

scipy.sparse.lil.lil_matrix

In [35]:
y_train.shape

(391, 6)

In [2]:
import numpy as np

In [36]:
# np.unique(y_train.rows).shape, np.unique(y_test.rows).shape

In [22]:
X_train.shape

(391, 72)

In [92]:
# Import BinaryRelevance from skmultilearn
from skmultilearn.problem_transform import BinaryRelevance

In [93]:
# Import SVC classifier from sklearn
from sklearn.svm import SVC

In [94]:
# Setup the classifier
classifier = BinaryRelevance(classifier=SVC(), require_dense=[False,True])

In [26]:
# Train
classifier.fit(X_train, y_train)

D:\Dev\Miniconda3\envs\dl\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\Dev\Miniconda3\envs\dl\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\Dev\Miniconda3\envs\dl\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\Dev\Miniconda3\envs\dl\lib\site-packages\sklearn\svm\base.py:193: FutureW

BinaryRelevance(classifier=SVC(C=1.0, cache_size=200, class_weight=None,
                               coef0=0.0, decision_function_shape='ovr',
                               degree=3, gamma='auto_deprecated', kernel='rbf',
                               max_iter=-1, probability=False,
                               random_state=None, shrinking=True, tol=0.001,
                               verbose=False),
                require_dense=[False, True])

In [27]:
# Predict
y_pred = classifier.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score

In [32]:
import sklearn.metrics as metrics

In [34]:
metrics.hamming_loss(y_test, y_pred)

0.26485148514851486

In [20]:
# dataset = arff.load(open('d:\datasets\TF_knockdown_2_MEKA.arff', 'rt'))

In [17]:
from scipy.io import arff

In [58]:
data, meta = arff.loadarff('d:\datasets\TF_knockdown_2_MEKA.arff')

In [66]:
import pandas as pd

In [67]:
df = pd.DataFrame(data=data)

In [68]:
df.head()

class1 class2 class3 class4 class5 class6 class7 class8 class9  \
0   b'1'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   
1   b'1'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   
2   b'1'   b'0'   b'0'   b'0'   b'1'   b'0'   b'0'   b'0'   b'0'   
3   b'1'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   b'0'   
4   b'1'   b'0'   b'0'   b'0'   b'0'   b'1'   b'0'   b'0'   b'0'   

   CGR8.Arhgef11  ...  N2A.Slain2  N2A.Spag9  N2A.Ssbp3  N2A.Tbc1d23  \
0       0.283451  ...   -0.102761  -0.084580  -0.440413    -2.576737   
1       0.427489  ...   -0.121880  -0.423803  -0.196789    -4.599442   
2      -0.326574  ...   -0.507111  -2.831249  -1.408496    -4.038101   
3      -0.249097  ...   -0.359208  -1.934674  -1.062874    -1.233482   
4      -0.050508  ...   -0.205232   0.439393   0.691657    -8.064449   

   N2A.Tead1.A1  N2A.Tead1.A3  N2A.Ubtf  N2A.Uspl1.A1  N2A.Uspl1.A2  N2A.Xpo4  
0      0.191635      0.332387  0.661686      0.605076      0.483252 -0.282253  
1      0.317337      0.171973  0.078284     -0.116500     -0.663218 -0.418863  
2      0.456082     -0.798436  2.139795     -0.182573     -1.462759 -0.131938  
3     -0.399310     -0.161637  1.201784      0.354757      2.193761 -0.286259  
4     -0.813852      0.141126  2.115329     -0.295683      1.083714  0.241679  

[5 rows x 108 columns]

In [84]:
df.iloc[0:4, 0:9].values.astype(np.int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [85]:
y_tf_train = df.iloc[:, 0:9].values.astype(np.int)

In [86]:
y_tf_train.shape

(158, 9)

In [87]:
x_tf_train = df.iloc[:, 9:].values

In [88]:
x_tf_train.shape

(158, 99)

In [95]:
# Train
classifier.fit(x_tf_train, y_tf_train)

D:\Dev\Miniconda3\envs\dl\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\Dev\Miniconda3\envs\dl\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\Dev\Miniconda3\envs\dl\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
D:\Dev\Miniconda3\envs\dl\lib\site-packages\sklearn\svm\base.py:193: FutureW

BinaryRelevance(classifier=SVC(C=1.0, cache_size=200, class_weight=None,
                               coef0=0.0, decision_function_shape='ovr',
                               degree=3, gamma='auto_deprecated', kernel='rbf',
                               max_iter=-1, probability=False,
                               random_state=None, shrinking=True, tol=0.001,
                               verbose=False),
                require_dense=[False, True])

In [98]:
y_pred_test = classifier.predict(x_tf_train[0])

In [101]:
y_pred_test.toarray()

array([[1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [11]:
test_idx_cache = np.empty((3,9))

In [12]:
test_idx_cache.shape

(3, 9)

In [13]:
test_idx_cache

array([[6.23042070e-307, 2.22523004e-307, 3.22651328e-307,
        8.45599366e-307, 7.56593017e-307, 1.33511290e-306,
        8.90092016e-307, 1.11261027e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.11260483e-306, 1.11260755e-306, 1.42417629e-306,
        2.22523140e-306, 1.42421160e-306, 9.34601642e-307],
       [1.06811422e-306, 6.89806849e-307, 1.78021391e-306,
        6.23037996e-307, 7.56603881e-307, 1.69118787e-306,
        8.34451503e-308, 2.22813476e-312, 2.22813476e-312]])

In [14]:
np.delete(test_idx_cache, 0, axis=0)

array([[1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.11260483e-306, 1.11260755e-306, 1.42417629e-306,
        2.22523140e-306, 1.42421160e-306, 9.34601642e-307],
       [1.06811422e-306, 6.89806849e-307, 1.78021391e-306,
        6.23037996e-307, 7.56603881e-307, 1.69118787e-306,
        8.34451503e-308, 2.22813476e-312, 2.22813476e-312]])

In [15]:
test_idx_cache

array([[6.23042070e-307, 2.22523004e-307, 3.22651328e-307,
        8.45599366e-307, 7.56593017e-307, 1.33511290e-306,
        8.90092016e-307, 1.11261027e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.11260483e-306, 1.11260755e-306, 1.42417629e-306,
        2.22523140e-306, 1.42421160e-306, 9.34601642e-307],
       [1.06811422e-306, 6.89806849e-307, 1.78021391e-306,
        6.23037996e-307, 7.56603881e-307, 1.69118787e-306,
        8.34451503e-308, 2.22813476e-312, 2.22813476e-312]])

In [18]:
np.concatenate((test_idx_cache, np.zeros((1, 9))), axis=0)

array([[6.23042070e-307, 2.22523004e-307, 3.22651328e-307,
        8.45599366e-307, 7.56593017e-307, 1.33511290e-306,
        8.90092016e-307, 1.11261027e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.11260483e-306, 1.11260755e-306, 1.42417629e-306,
        2.22523140e-306, 1.42421160e-306, 9.34601642e-307],
       [1.06811422e-306, 6.89806849e-307, 1.78021391e-306,
        6.23037996e-307, 7.56603881e-307, 1.69118787e-306,
        8.34451503e-308, 2.22813476e-312, 2.22813476e-312],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])