In [1]:
import numpy as np
import scipy.sparse as sp
import pickle as pkl
import sys
import pandas as pd

###  use pkl.load() get matrix

In [2]:
names = ['x', 'y', 'tx', 'ty', 'allx', 'ally', 'graph']
objects = []
for i in range(len(names)):
    with open("gcn/data/ind.{}.{}".format('cora', names[i]), 'rb') as f:
        if sys.version_info > (3, 0):
            objects.append(pkl.load(f, encoding='latin1'))
        else:
            objects.append(pkl.load(f))

x, y, tx, ty, allx, ally, graph = tuple(objects)

In [21]:
# print(allx) # ind.cora.x

  (0, 19)	1.0
  (0, 81)	1.0
  (0, 146)	1.0
  (0, 315)	1.0
  (0, 774)	1.0
  (0, 877)	1.0
  (0, 1194)	1.0
  (0, 1247)	1.0
  (0, 1274)	1.0
  (1, 19)	1.0
  (1, 88)	1.0
  (1, 149)	1.0
  (1, 212)	1.0
  (1, 233)	1.0
  (1, 332)	1.0
  (1, 336)	1.0
  (1, 359)	1.0
  (1, 472)	1.0
  (1, 507)	1.0
  (1, 548)	1.0
  (1, 687)	1.0
  (1, 763)	1.0
  (1, 808)	1.0
  (1, 889)	1.0
  (1, 1058)	1.0
  :	:
  (1706, 1236)	1.0
  (1706, 1242)	1.0
  (1706, 1320)	1.0
  (1706, 1337)	1.0
  (1707, 4)	1.0
  (1707, 118)	1.0
  (1707, 153)	1.0
  (1707, 180)	1.0
  (1707, 228)	1.0
  (1707, 699)	1.0
  (1707, 701)	1.0
  (1707, 719)	1.0
  (1707, 750)	1.0
  (1707, 758)	1.0
  (1707, 810)	1.0
  (1707, 911)	1.0
  (1707, 1177)	1.0
  (1707, 1233)	1.0
  (1707, 1251)	1.0
  (1707, 1257)	1.0
  (1707, 1262)	1.0
  (1707, 1299)	1.0
  (1707, 1325)	1.0
  (1707, 1386)	1.0
  (1707, 1397)	1.0


In [25]:
# all_x_d = sp.csr_matrix(allx)

In [28]:
# print(all_x_d.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
all_x = sp.csr_matrix(allx)
all_y = sp.csr_matrix(ally)

In [9]:
df_x = pd.DataFrame(all_x.toarray())
df_y = pd.DataFrame(all_y.toarray())

In [12]:
print(type(graph))

<class 'collections.defaultdict'>


In [18]:
import json
json.dump(graph, open('ind.cora.graph.json', 'w'))

### labels and features matrix save to csv

In [16]:
df_x.to_csv('ind.cora.allx.csv')
df_y.to_csv('ind.cora.ally.csv')