In [1]:
import numpy as np
import scipy.sparse as sp
import pickle as pkl
import sys
import pandas as pd

###  use pkl.load() get matrix

In [2]:
names = ['x', 'y', 'tx', 'ty', 'allx', 'ally', 'graph']
objects = []
for i in range(len(names)):
    with open("../gcn/data/ind.{}.{}".format('cora', names[i]), 'rb') as f:
        if sys.version_info > (3, 0):
            objects.append(pkl.load(f, encoding='latin1'))
        else:
            objects.append(pkl.load(f))

x, y, tx, ty, allx, ally, graph = tuple(objects)

In [15]:
# print(allx) # ind.cora.x

In [25]:
# all_x_d = sp.csr_matrix(allx)

In [28]:
# print(all_x_d.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
all_x = sp.csr_matrix(allx)
all_y = sp.csr_matrix(ally)

In [9]:
df_x = pd.DataFrame(all_x.toarray())
df_y = pd.DataFrame(all_y.toarray())

In [12]:
print(type(graph))

<class 'collections.defaultdict'>


In [18]:
import json
json.dump(graph, open('ind.cora.graph.json', 'w'))

### labels and features matrix save to csv

In [16]:
df_x.to_csv('ind.cora.allx.csv')
df_y.to_csv('ind.cora.ally.csv')