In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("d://datasets//peptide_caps_net.csv", )

In [4]:
print(df)

      Class Samples  f1  f2  f3  f4  f5  f6  f7  f8  ...   f391  f392  f393  \
0         2     NS1   0   0   0   0   0   0   0   0  ...      0     0     0   
1         2    NS10   0   0   0   0   0   0   0   0  ...      0     0     0   
2         2   NS100   1   0   0   0   0   0   0   0  ...      0     0     0   
3         2  NS1000   0   0   0   0   0   0   0   0  ...      0     0     0   
4         2  NS1001   0   0   0   0   0   0   0   0  ...      0     0     0   
5         2  NS1002   0   0   0   0   0   0   0   1  ...      0     0     0   
6         2  NS1003   0   0   0   0   1   0   0   0  ...      0     0     0   
7         2  NS1004   0   0   0   0   0   0   0   0  ...      0     0     0   
8         2  NS1005   0   0   0   0   0   0   0   0  ...      0     0     0   
9         2  NS1006   0   0   0   0   0   0   0   0  ...      0     0     0   
10        2  NS1007   0   0   0   0   0   0   0   0  ...      0     0     0   
11        2  NS1008   0   1   0   0   0   0   0   0 

In [5]:
print(df['Class'])

0       2
1       2
2       2
3       2
4       2
5       2
6       2
7       2
8       2
9       2
10      2
11      2
12      2
13      2
14      2
15      2
16      2
17      2
18      2
19      2
20      2
21      2
22      2
23      2
24      2
25      2
26      2
27      2
28      2
29      2
       ..
6064    1
6065    1
6066    1
6067    1
6068    1
6069    1
6070    1
6071    1
6072    1
6073    1
6074    1
6075    1
6076    1
6077    1
6078    1
6079    1
6080    1
6081    1
6082    1
6083    1
6084    1
6085    1
6086    1
6087    1
6088    1
6089    1
6090    1
6091    1
6092    1
6093    1
Name: Class, Length: 6094, dtype: int64


In [12]:
print(df.values[:,0])

[2 2 2 ... 1 1 1]


In [13]:
labels = df.values[:,0]

In [14]:
features = df.values[:,2:]

In [15]:
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [19]:
features.shape[0]

6094

In [20]:
new_features = features.reshape((features.shape[0], 20, 20))

In [21]:
new_features.shape

(6094, 20, 20)

In [22]:
new_features[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0,

In [23]:
features.sum

<function ndarray.sum>

In [24]:
dataset = (labels, new_features)

In [25]:
dataset.shape

AttributeError: 'tuple' object has no attribute 'shape'

In [26]:
len(dataset)

2

In [27]:
dataset.count

<function tuple.count>