In [2]:
import torch # pytorch
import numpy as np
import pandas as pd

In [2]:
x = torch.rand(4, 4)

In [3]:
print(x)


 0.7314  0.6649  0.1999  0.2093
 0.2327  0.8479  0.8883  0.5416
 0.6623  0.5208  0.8937  0.5167
 0.9389  0.6619  0.1746  0.8430
[torch.FloatTensor of size 4x4]



In [4]:
y = x.view(-1, 8)

In [5]:
print(y)


 0.7314  0.6649  0.1999  0.2093  0.2327  0.8479  0.8883  0.5416
 0.6623  0.5208  0.8937  0.5167  0.9389  0.6619  0.1746  0.8430
[torch.FloatTensor of size 2x8]



In [9]:
z = x.view(8, -1)

In [10]:
print(z)


 0.7314  0.6649
 0.1999  0.2093
 0.2327  0.8479
 0.8883  0.5416
 0.6623  0.5208
 0.8937  0.5167
 0.9389  0.6619
 0.1746  0.8430
[torch.FloatTensor of size 8x2]



In [13]:
print(z[:, 1])


 0.6649
 0.2093
 0.8479
 0.5416
 0.5208
 0.5167
 0.6619
 0.8430
[torch.FloatTensor of size 8]



In [14]:
a = x.numpy()
print(a)

[[0.73136836 0.664861   0.19985789 0.20925856]
 [0.2327025  0.8479016  0.88832366 0.5416304 ]
 [0.6623129  0.52077496 0.8936885  0.51671296]
 [0.93889314 0.6619363  0.17463416 0.8429976 ]]


In [17]:
b = np.linspace(1, 5)
tensor_b = torch.from_numpy(b)
print(tensor_b.view(5, -1))


 1.0000  1.0816  1.1633  1.2449  1.3265  1.4082  1.4898  1.5714  1.6531  1.7347
 1.8163  1.8980  1.9796  2.0612  2.1429  2.2245  2.3061  2.3878  2.4694  2.5510
 2.6327  2.7143  2.7959  2.8776  2.9592  3.0408  3.1224  3.2041  3.2857  3.3673
 3.4490  3.5306  3.6122  3.6939  3.7755  3.8571  3.9388  4.0204  4.1020  4.1837
 4.2653  4.3469  4.4286  4.5102  4.5918  4.6735  4.7551  4.8367  4.9184  5.0000
[torch.DoubleTensor of size 5x10]



In [3]:
DATASETS = "peptide_caps_net.csv"
df = pd.read_csv(DATASETS)

In [4]:
labels = df.values[:, 0].astype(np.int32)  # 第一列为分类标注名称
features = df.values[:, 2:].astype(np.int32)

In [5]:
labels

array([2, 2, 2, ..., 1, 1, 1], dtype=int32)

In [6]:
t_labels = torch.from_numpy(labels)
t_features = torch.from_numpy(features).contiguous().view(-1, 20, 20) # 返回一个内存连续的有相同数据的tensor，否则无法做reshape

In [11]:
print(t_features.size())
print(t_labels.size())
print(type(t_labels))
print(type(t_features))
print(t_labels[1:3])

torch.Size([6094, 20, 20])
torch.Size([6094])
<class 'torch.IntTensor'>
<class 'torch.IntTensor'>

 2
 2
[torch.IntTensor of size 2]

